<?php

namespace P4\BilletBundle\Repository;

/**
 * BilletsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BilletsRepository extends \Doctrine\ORM\EntityRepository
{
    public function countNbBilletPerDate(\DateTime $date)
    {
        $qb = $this->createQueryBuilder('t')
            ->select('count(t.date)')
            ->where('t.date = :date')
            ->setParameter('date', $date);

        return intval($qb->getQuery()->getSingleScalarResult());
    }
}