p4_billet_homepage:
    path:     /
    defaults: { _controller: P4BilletBundle:Formulaire:index }

p4_billet_commande:
    path: /paiement
    defaults: { _controller: P4BilletBundle:Formulaire:paiement}