services:
#    p4_billet.example:
#        class: P4\BilletBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    #p4_billet.calculs:
        #class: P4\BilletBundle\Calculs\P4Calculs

    p4_billet.forms:
        class: P4\BilletBundle\Forms\P4Forms
    
    p4_billet.limitbilletday:
        class: P4\BilletBundle\Validator\Constraints\LimitBilletDayValidator
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: validator.constraint_validator, alias: p4_billet_limitbilletday }